name: CI/CD Pipeline

on:
  push:
    branches: [ "11.x" ]

jobs:
  project-deploy:
    runs-on: self-hosted

    steps:
    - name: Update Local Repo
      run: cd /home/azureuser/laravel && git pull
    - name: Install Dependencies
      run: cd /home/azureuser/laravel && composer install --no-interaction --prefer-dist --optimize-autoloader
    - name: Run 
      run: cd /home/azureuser/laravel && php artisan migrate --force
